#H2 Server Properties
#Thu Oct 09 12:17:08 GMT 2025
0=JHipster H2 (Memory)|org.h2.Driver|jdbc\:h2\:mem\:caissavance2|caissavance2
1=JHipster H2 (Disk)|org.h2.Driver|jdbc\:h2\:file\:./target/h2db/db/caissavance2|caissavance2
webAllowOthers=true
webPort=8092
webSSL=false
